#ifndef __DEF_ATTRIBUTE_H_
#define __DEF_ATTRIBUTE_H_

#include "CommonDefine.h"

// 生物体类型
enum AttributeType
{
	ATTRIBUTE_INVIEWRANGE,
	ATTRIBUTE_OUTVIEWRANGE,

	ATTRIBUTE_STATUS,
	ATTRIBUTE_LEVEL,
	ATTRIBUTE_RED,
	ATTRIBUTE_REDMAX,
	ATTRIBUTE_BLUE,
	ATTRIBUTE_BLUEMAX,
	ATTRIBUTE_EXP,
	ATTRIBUTE_SPEED,
	ATTRIBUTE_REDRECOVER,
	ATTRIBUTE_BLUERECOVER,
	ATTRIBUTE_PHYSICATTACK,
	ATTRIBUTE_PHYSICDEFEND,
	ATTRIBUTE_SPELLATTACK,
	ATTRIBUTE_SPELLDEFEND,
	ATTRIBUTE_WULI,
	ATTRIBUTE_SHENSHOU,
	ATTRIBUTE_NEILI,
	ATTRIBUTE_ATTACKTYPE,
	ATTRIBUTE_MINGZHONGLV,
	ATTRIBUTE_SHANBILV,
	ATTRIBUTE_BAOJI,
	ATTRIBUTE_BAOJILV,
	ATTRIBUTE_GEDANG,
	ATTRIBUTE_GEDANGLV,
	ATTRIBUTE_DEATTACK,
	ATTRIBUTE_DEMELEEATTACK,
	ATTRIBUTE_DEREMOTEATTACK,
	ATTRIBUTE_DESPELLCD,
	ATTRIBUTE_ATTACKREDRECOVER,
	ATTRIBUTE_ATTACKBLUERECOVER,
	ATTRIBUTE_SPELLCD_1,
	ATTRIBUTE_SPELLCD_2,
	ATTRIBUTE_SPELLCD_3,
	ATTRIBUTE_SPELLCD_4,

	ATTRIBUTE_MAX,
};

typedef boost::function<void(const ValueType& vOldValue, const ValueType& vNewValue)> AttributeHandler;

// 属性偏移结构
struct AttributeOffset
{
	void*					nOffset;				// 属性位置
	int32					nSize;					// 属性大小
	bool					bCanSet;				// 是否可设置
	AttributeHandler		hHandler;				// 属性修改回调
};


#endif
